pipeline:
  name: meshcentral-vanilla
  identifier: meshcentralvanilla
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: meshcentral
        build: <+input>
  stages:
    - stage:
        name: CodeQL-Build
        identifier: CodeQLBuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install CodeQL
                  identifier: Build
                  spec:
                    shell: Sh
                    command: |
                      echo "deb [arch=amd64] https://pkg.github.com/github/codeql-cli-deb stable main" | sudo tee /etc/apt/sources.list.d/github-codeql.list
                      curl -L https://github.com/github/codeql-cli-deb/releases/download/v2.0.0/codeql_2.0.0_amd64.deb -o codeql.deb
                      sudo dpkg -i codeql.deb
              - step:
                  type: Plugin
                  name: Initialize CodeQL
                  identifier: Initialize_CodeQL
                  spec:
                    connectorRef: account.harnessImage
                    image: plugins/github-actions
                    settings:
                      uses: github/codeql-action/init@v1
              - step:
                  type: Plugin
                  name: Perform CodeQL Analysis
                  identifier: Perform_CodeQL_Analysis
                  spec:
                    connectorRef: account.harnessImage
                    image: plugins/github-actions
                    settings:
                      uses: github/codeql-action/analyze@v1
                  when:
                    stageStatus: All
                  failureStrategies: []
