pipeline:
  name: test-meshcentral
  identifier: testmeshcentral
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: MeshCentral
        build: <+input>
  stages:
    - stage:
        name: Deploy Docs
        identifier: Deploy_Docs
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Plugin
                  name: deploy
                  identifier: deploy
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    settings:
                      uses: actions/setup-python@v2
                      with:
                        python-version: 3.x
              - step:
                  type: Run
                  name: deploy docs
                  identifier: deploy_docs
                  spec:
                    shell: Sh
                    command: |-
                      pip install --upgrade pip
                      pip install --upgrade setuptools wheel
                      pip install mkdocs mkdocs-material pymdown-extensions
                      mkdocs gh-deploy --force
                  when:
                    stageStatus: All
                  failureStrategies: []
          sharedPaths:
            - /docs/
    - stage:
        name: codeql-analysis
        identifier: codeqlanalysis
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Plugin
                  name: Perform CodeQL Analysis
                  identifier: Perform_CodeQL_Analysis
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    settings:
                      uses: github/codeql-action/analyze@v1
              - step:
                  type: Plugin
                  name: Initialize CodeQL
                  identifier: Initialize_CodeQL
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    settings:
                      uses: github/codeql-action/init@v1
        when:
          pipelineStatus: All
    - stage:
        name: Docker
        identifier: Docker
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: token
                  identifier: token
                  spec:
                    shell: Sh
                    command: echo "::set-output name=defined::true"
                    envVariables:
                      REGISTRY: ghcr.io
                    outputVariables:
                      - name: token
              - step:
                  type: Plugin
                  name: Checkout
                  identifier: Checkout
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    settings:
                      uses: actions/checkout@v3
                      with:
                        fetch-depth: 0
              - step:
                  type: Plugin
                  name: Set up QEMU
                  identifier: Set_up_QEMU
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    settings:
                      uses: docker/setup-qemu-action@v2
              - step:
                  type: Plugin
                  name: Set up Docker Buildx
                  identifier: Set_up_Docker_Buildx
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    settings:
                      uses: ocker/setup-buildx-action@v2
              - step:
                  type: Plugin
                  name: Log in to the Container registry
                  identifier: Log_in_to_the_Container_registry
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    settings:
                      uses: docker/login-action@v2
                      with:
                        registry: <+pipeline.variables.REGISTRY>
        when:
          pipelineStatus: All
